version: "3"

services:
  {{ cookiecutter.project_slug }}:
    build: .
    container_name: {{ cookiecutter.project_slug }}
    env_file: .env
    tty: true
    entrypoint: ash
    volumes:
      - .:/{{ cookiecutter.project_slug }}
