[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "{{ cookiecutter.version }}"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.author}} <{{cookiecutter.email}}>"]
packages = [ {include = "{{ cookiecutter.project_slug }}"}]

[tool.poetry.dependencies]
python = "^3.10"
setuptools = "^57.4.0"
pytest = {version = "^6.2.4", extras = ["test"]}
{% if cookiecutter.use_dotenv == 'y' %}python-dotenv = "^0.19.2"{%- endif %}


[tool.poetry.dev-dependencies]
pytest = {version = "^6.2.4"}
black = {version = "^22.3.0", allow-prereleases = true}
isort = {version = "^5.10.1", allow-prereleases = true}
ipdb = {version = "^0.13.9", allow-prereleases = true}

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.poetry.scripts]
test = 'pytest:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
